-- ============================================================
-- مشروع أجيال الإيمان — إنشاء جداول Supabase كاملة
-- نفّذ هذا الملف كاملاً في: Supabase Dashboard → SQL Editor → New query
-- (الترتيب مهم: الأغلفة أولاً لأن باقي الجداول ترتبط بها عبر cover_id)
-- ملاحظة: RLS غير مفعّل في هذا السكربت عمدًا — لو احتجت سياسات أمان
-- (RLS Policies) لاحقًا، اطلبها في رسالة منفصلة.
-- ============================================================

-- ══════════════════════════════════════════════════════════════
-- 1) الأغلفة (الجدول الأساسي — كل المحتوى يرتبط به)
-- ══════════════════════════════════════════════════════════════
create table if not exists public.covers (
  id           bigint generated by default as identity primary key,
  title        text not null,
  cover_url    text,                   -- رابط الغلاف الأساسي (يُعرض لو لم يوجد غلاف مخصص للفئة)
  -- أغلفة مخصصة لكل فئة عمرية (اختياري — لو فارغ يُستخدم cover_url كبديل)
  cover_children_url  text,            -- غلاف مخصص للأطفال
  cover_teens_url     text,            -- غلاف مخصص للمراهقين
  cover_adults_url    text,            -- غلاف مخصص للكبار
  section_type text not null
               check (section_type in ('books','anime','cartoon','courses','cartoon_stories','religious_content')),
  description  text,
  category     text,                   -- قيم مفصولة بفواصل، مثال: 'children,teens'
  created_at   timestamptz not null default now()
);

-- ══════════════════════════════════════════════════════════════
-- 2) الكتب والكتب الصوتية
-- ══════════════════════════════════════════════════════════════
create table if not exists public.books (
  id            bigint generated by default as identity primary key,
  cover_id      bigint references public.covers(id) on delete cascade,
  title         text not null,
  author        text,
  category      text,                  -- 'children' | 'teens' | 'adults'
  book_type     text,                  -- 'pdf' | 'text'
  file_url      text,                  -- رابط ملف الـ PDF من Internet Archive
  youtube_url   text,
  is_audio_book boolean not null default false,
  audio_url     text,                  -- رابط الملف الصوتي المرفوع على Internet Archive
  duration      text,
  created_at    timestamptz not null default now()
);
create index if not exists idx_books_cover_id on public.books(cover_id);

-- ══════════════════════════════════════════════════════════════
-- 3) عروض الأنمي والكرتون
-- ══════════════════════════════════════════════════════════════
create table if not exists public.anime_shows (
  id             bigint generated by default as identity primary key,
  cover_id       bigint references public.covers(id) on delete cascade,
  title          text not null,
  description    text,
  category       text,                 -- 'children' | 'teens'
  show_type      text,                 -- 'anime' | 'cartoon'
  display_cover  boolean not null default false,
  created_at     timestamptz not null default now()
);
create index if not exists idx_anime_shows_cover_id on public.anime_shows(cover_id);

-- ══════════════════════════════════════════════════════════════
-- 4) حلقات الأنمي (ترث غلافها من الأنمي → الأغلفة تلقائياً)
-- ══════════════════════════════════════════════════════════════
create table if not exists public.episodes (
  id             bigint generated by default as identity primary key,
  show_id        bigint references public.anime_shows(id) on delete cascade,
  title          text not null,
  episode_number integer not null default 0,
  video_url      text,                  -- رابط الفيديو من YouTube أو Pixeldrain أو Internet Archive
  created_at     timestamptz not null default now()
);
create index if not exists idx_episodes_show_id on public.episodes(show_id);

-- ══════════════════════════════════════════════════════════════
-- 5) الكورسات
-- ══════════════════════════════════════════════════════════════
create table if not exists public.courses (
  id           bigint generated by default as identity primary key,
  cover_id     bigint references public.covers(id) on delete cascade,
  title        text not null,
  description  text,
  course_link  text,
  created_at   timestamptz not null default now()
);
create index if not exists idx_courses_cover_id on public.courses(cover_id);

-- ══════════════════════════════════════════════════════════════
-- 6) الألعاب (بدون غلاف — أزرار مباشرة)
-- ══════════════════════════════════════════════════════════════
create table if not exists public.games (
  id         bigint generated by default as identity primary key,
  title      text not null,
  game_url   text not null,
  created_at timestamptz not null default now()
);

-- ══════════════════════════════════════════════════════════════
-- 7) القصص الكرتونية
-- ══════════════════════════════════════════════════════════════
create table if not exists public.cartoon_stories (
  id           bigint generated by default as identity primary key,
  cover_id     bigint references public.covers(id) on delete cascade,
  title        text not null,
  content_text text,
  images       text[],                 -- مصفوفة روابط صور
  category     text,                   -- 'children' | 'teens'
  video_url    text,                   -- رابط الفيديو من يوتيوب أو Pixeldrain أو Internet Archive
  created_at   timestamptz not null default now()
);
create index if not exists idx_cartoon_stories_cover_id on public.cartoon_stories(cover_id);

-- ══════════════════════════════════════════════════════════════
-- 8) المحتوى الديني
-- ══════════════════════════════════════════════════════════════
create table if not exists public.religious_content (
  id           bigint generated by default as identity primary key,
  cover_id     bigint references public.covers(id) on delete cascade,
  title        text not null,
  content_text text,
  content_type text,                   -- 'video' | 'audio' | 'article'
  media_url    text,                  -- رابط الوسائط من يوتيوب أو Pixeldrain أو Internet Archive
  created_at   timestamptz not null default now()
);
create index if not exists idx_religious_content_cover_id on public.religious_content(cover_id);

-- ══════════════════════════════════════════════════════════════
-- 9) إعدادات الأقسام (يقرأها تطبيق الموبايل)
-- ══════════════════════════════════════════════════════════════
create table if not exists public.category_settings (
  id           bigint generated by default as identity primary key,
  category_key text not null unique,   -- 'children' | 'teens' | 'adults'
  title_ar     text,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now()
);

-- تعبئة مبدئية للفئات الثلاث (آمنة لو شغّلت السكربت أكثر من مرة)
insert into public.category_settings (category_key, title_ar, is_active) values
  ('children', 'الأطفال',    true),
  ('teens',    'المراهقين',  true),
  ('adults',   'الكبار',     true)
on conflict (category_key) do nothing;

-- ══════════════════════════════════════════════════════════════
-- 10) المستخدمون المسموح لهم بدخول لوحة التحكم
-- id هنا هو نفس User UID من Supabase Authentication
-- ══════════════════════════════════════════════════════════════
create table if not exists public.admins (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null,
  username    text,
  role        text not null default 'admin' check (role in ('super_admin','admin')),
  permissions text[],
  is_active   boolean not null default false,
  created_at  timestamptz not null default now()
);

-- ══════════════════════════════════════════════════════════════
-- 11) إعدادات التطبيق (صف واحد فقط دائمًا id = 1)
-- ══════════════════════════════════════════════════════════════
create table if not exists public.app_settings (
  id                  bigint generated by default as identity primary key,
  contact_link        text,
  donate_link         text,
  volunteer_link      text,
  site_logo_url       text,
  custom_ad_image_url text,
  custom_ad_link      text,
  google_adsense_code text,
  ad_top_code         text,
  ad_top_width        text,
  ad_top_height       text,
  ad_mid_code         text,
  ad_mid_width        text,
  ad_mid_height       text,
  ad_modal_code       text,
  ad_modal_width      text,
  ad_modal_height     text,
  app_name            text,
  app_logo_url        text,
  created_at          timestamptz not null default now(),
  constraint app_settings_single_row check (id = 1)
);

insert into public.app_settings (id) values (1)
on conflict (id) do nothing;

-- ══════════════════════════════════════════════════════════════
-- باتش: إضافة أعمدة أغلفة الفئات العمرية لو الجدول موجود مسبقاً
-- (آمن لإعادة التشغيل — لن يمسح أي بيانات)
-- ══════════════════════════════════════════════════════════════
alter table public.covers
  add column if not exists cover_children_url  text,
  add column if not exists cover_teens_url     text,
  add column if not exists cover_adults_url    text;

-- حذف قيود التحقق القديمة التي تمنع اختيار فئتين معاً (مثل children,teens)
alter table public.covers drop constraint if exists covers_category_check;

-- باتش: أعمدة app_settings الاحتياطية (للتوافق مع السكربتات القديمة)
alter table public.app_settings
  add column if not exists site_logo_url       text,
  add column if not exists ad_top_code         text,
  add column if not exists ad_top_width        text,
  add column if not exists ad_top_height       text,
  add column if not exists ad_mid_code         text,
  add column if not exists ad_mid_width        text,
  add column if not exists ad_mid_height       text,
  add column if not exists ad_modal_code       text,
  add column if not exists ad_modal_width      text,
  add column if not exists ad_modal_height     text,
  add column if not exists app_name            text,
  add column if not exists app_logo_url        text,
  add column if not exists supabase_url        text,
  add column if not exists supabase_anon_key   text;

-- باتش: إضافة عمود رابط الكورس الناقص
alter table public.courses
  add column if not exists course_link text;

-- باتش: إضافة عمود الرابط الخارجي المباشر (يُستخدم كزر "فتح" احتياطي عند عدم عمل المشغل)
alter table public.episodes
  add column if not exists external_url text;

alter table public.books
  add column if not exists external_url text;

alter table public.cartoon_stories
  add column if not exists external_url text;

alter table public.religious_content
  add column if not exists external_url text;

-- ============================================================
-- خطوة أخيرة يدوية (لازم تعملها بنفسك بعد تشغيل السكربت):
-- 1) أنشئ مستخدم من: Authentication → Users → Add user (بريد + كلمة مرور)
-- 2) انسخ User UID الظاهر له
-- 3) شغّل هذا السطر مع استبدال UUID والبريد بقيمك الحقيقية:
--
-- insert into public.admins (id, email, role, is_active)
-- values ('ضع-الـ-UUID-هنا', 'admin@example.com', 'super_admin', true);
-- ============================================================
